let a = [
    {
        "id": 885747837,
        "channel_id": 6593295,
        "last_mile_awb": null,
        "show_last_mile_label_download": 1,
        "last_mile_awb_track_url": null,
        "last_mile_courier_name": null,
        "channel_name": "WOC- World Of Care (Shopify)",
        "base_channel_code": "SH",
        "channel_order_id": "1010",
        // "customer_name": "graphic world",   
        // "customer_email": "graphicworld171@gmail.com",
        // "customer_phone": "8770819950",
        // "customer_address": "indore madhya pradesh",
        // "customer_address_2": "test",
        // "customer_city": "Sehore",
        // "customer_state": "Madhya Pradesh",
        // "customer_pincode": "466001",
        // "customer_country": "India",
        "customer_latitude": null,
        "customer_longitude": null,
        "customer_alternate_phone": "",
        "pickup_location": "Primary",
        "package_instructions": null,
        "order_type": null,
        // "payment_status": "paid",
        "total": "999.00",
        "tax": "0.00",
        "sla": "2 days",
        // "shipping_method": "SR",
        "ship_type": "",
        "rto_risk": "low",
        "return_pickup_data": "",
        "expedited": 0,
        // "status": "CANCELED",
        "status_code": 5,
        "eway_bill_number": "",
        "eway_required": false,
        "awd_etds": null,
        "master_status": "",
        // "payment_method": "prepaid",
        "cod_recieved_hover_text": "",
        "change_payment_mode": false,
        "is_international": 0,
        "document_status": 1,
        "international_b2b": "",
        "international_order_type": "",
        "is_order_custom": "",
        "purpose_of_shipment": 1,
        "channel_created_at": "6 Jul 2025, 01:11 AM",
        "created_at": "6 Jul 2025, 01:11 AM",
        "updated_at": "6 Jul 2025, 01:12 AM",
        "updated_on": "",
        "pickup_boy_name": "",
        "pickup_boy_contact_no": "",
        "products": [
            {
                "id": 1311880388,
                "channel_order_product_id": "15104046006441",
                // "name": "Woc Panchgavya Ayurvedic Herbal Hair Oil",
                "channel_sku": "44412894576809",
                "quantity": 1,
                "product_id": 213068212,
                "available": "0",
                "status": "CANCELED",
                // "price": "999.00",
                "product_cost": "999.00",
                "status_code": 5,
                "hsn": "",
                "is_allopathic": false,
                "discount": 0,
                "discount_including_tax": 0,
                "selling_price": 999,
                "mrp": 999,
                "tax_percentage": 0,
                "description": null
            }
        ],
        "shipments": [
            {
                "id": 882076329,
                "isd_code": "+91",
                "courier": "",
                "is_sr_recommended": false,
                "sr_courier_name": "",
                "courier_id": "",
                "shipping_charges": "",
                "weight": 0,
                "dimensions": "0x0x0",
                "shipped_date": null,
                "pickup_scheduled_date": "0000-00-00 00:00:00",
                "pickedup_timestamp": null,
                "pickup_token_number": null,
                "awb": "",
                "rto_awb": "",
                "return_awb": "",
                "volumetric_weight": 0,
                "pod": null,
                "etd": "0000-00-00 00:00:00",
                "saral_etd": "NA",
                "rto_delivered_date": "0000-00-00 00:00:00",
                "delivered_date": null,
                "etd_escalation_btn": false,
                "rto_initiated_date": "0000-00-00 00:00:00",
                "package_images": "",
                "weight_action": null,
                "status": 8,
                "pickup_id": "",
                "delivery_executive_name": "",
                "delivery_executive_number": "",
                "delay_reason": "",
                "product_quantity": 1,
                "total": "999.00",
                "sub_status": null,
                "cost": "0.00",
                "awb_assign_date": null
            }
        ],
        "cod": 0,
        "activities": [
            "ORDER_FETCHED",
            "CUSTOM",
            "CANCALLED_ON_SHIPROCKET_FROM_CHANNEL",
            "ORDER_CANCELLED"
        ],
        "allow_return": 0,
        "is_incomplete": 0,
        "errors": [],
        "pickup_exception_reason": "",
        "show_escalation_btn": 0,
        "is_via_indiapost_courier": false,
        "show_escalation_btn_international": 0,
        "escalation_status": "",
        "escalation_id": null,
        "pii_removed": 0,
        "allow_multiship": 0,
        "others": {
            "name": "#1010",
            "test": true,
            "token": "bc7f67f23e8946682bcee21d25e094e8",
            "weight": "",
            "gateway": "bogus",
            "refunds": [],
            "user_id": null,
            "closed_at": null,
            "confirmed": true,
            "reference": "",
            "tax_lines": [],
            "cart_token": "Z2NwLWFzaWEtc291dGhlYXN0MTowMUpaRTFITVdQU1hOTkYwQ1A0MFZFNDVFVA",
            "checkout_id": 29338912358569,
            "location_id": null,
            "source_name": "web",
            // "api_order_id": 6347680546985,
            "billing_city": "sehore",
            "billing_name": "graphic world",
            "cancelled_at": null,
            "company_name": null,
            "payment_code": "bogus",
            "billing_email": "graphicworld171@gmail.com",
            "billing_phone": "8770819950",
            "billing_state": "Madhya Pradesh",
            "cancel_reason": null,
            "contact_email": "graphicworld171@gmail.com",
            "currency_code": "INR",
            "checkout_token": "929ba4a081883a5a595ded69306e3f03",
            "customer_gstin": null,
            "discount_codes": [],
            "referring_site": "",
            "subtotal_price": "999.00",
            "taxes_included": true,
            "billing_address": "indore madhya pradesh",
            "billing_company": null,
            "billing_country": "India",
            "billing_pincode": "466001",
            "note_attributes": [],
            "billing_isd_code": null,
            "is_webhook_order": true,
            "shipping_charges": "0.00",
            "billing_address_2": "test",
            "is_order_verified": 0,
            "is_webhook_update": true,
            "order_verified_at": "",
            "processing_method": "",
            "srf_shipping_meta": "",
            "fulfillment_status": null,
            "payment_gateway_names": [
                "bogus"
            ],
            "store_rush_promise_sla": "",
            "billing_alternate_phone": "",
            "buyer_accepts_marketing": true,
            "checkout_shipping_title": "",
            "checkout_shipping_method": "Standard",
            "utm_and_tracking_details": "{\"status\":\"\",\"awb\":\"\",\"tracking_url\":\"\",\"tracking_company\":\"\"}"
        },
        "package_list": {
            "packages": [],
            "selected": false,
            "select_item": false,
            "all_packages": []
        },
        "pickup_address_detail": {
            "id": 7766292,
            "pickup_code": "Primary",
            "gstin": null,
            "invoice_prefix": null,
            "invoice_serial": null,
            "address": "33A, MPIDC, Industrial Area ",
            "address_2": "Badiyakhedi",
            "address_type": null,
            "city": "Sehore",
            "state": "Madhya Pradesh",
            "country": "India",
            "pin_code": "466001",
            "email": null,
            "phone": "",
            "phone_verified": 0,
            "alternate_phone": null,
            "name": null,
            "company_id": 6011441,
            "status": 2,
            "rto_address_id": null,
            "delhivery_clientware_id": null,
            "delhivery_surface_clientware_id": null,
            "delhivery_surface_standard_clientware_id": null,
            "delhivery_surface_lite_clientware_id": null,
            "delhivery_surface_10kg_clientware_id": null,
            "delhivery_surface_20kg_clientware_id": null,
            "sx_delhivery_clientware_id": null,
            "sx_delhivery_surface_clientware_id": null,
            "sx4_delhivery_surface_clientware_id": null,
            "sx3_delhivery_surface_clientware_id": null,
            "sx2_delhivery_surface_clientware_id": null,
            "sx1_delhivery_surface_clientware_id": null,
            "created_at": "2025-04-06T09:05:54.000000Z",
            "updated_at": "2025-04-06T09:05:54.000000Z",
            "gati_surface_customer_vendor_code": null,
            "gati_sg_customer_vendor_code": null,
            "delhivery_flash_air_clientware_id": null,
            "updated_on": "2025-04-06 09:05:54",
            "lat": null,
            "long": null,
            "delhivery_essential_5kg_clientware_id": null,
            "warehouse_code": null,
            "gati_surface_10kg_customer_vendor_code": null,
            "extra_info": null,
            "delhivery_documents_clientware_id": null,
            "delhivery_documents_250gm_clientware_id": null
        },
        "rto_address": [],
        "re_escalate": 0,
        "seller_request": null,
        "engage": "NA",
        "total_dead_weight": null,
        "total_volumetric_weight": null,
        "total_order_value": null,
        "boxes": null,
        "order_tag": [],
        "international_order_tag": [],
        "is_return": 0,
        "is_b2b": false,
        "is_insurance_opt": false,
        "has_calls": false,
        "pickup_booked_date": null,
        "delivery_delayed": false,
        "delay_reason": "",
        "delay_reason_code": "",
        "etd_date": null,
        "out_for_delivery_date": null,
        "delivered_date": null,
        "product_quantity": 1,
        "rto_prediction": "",
        "rto_show": 0,
        "rto_reason": "",
        "rto_escalate": 0,
        "rto_re_escalate": 0,
        "rto_escalate_history": 0,
        "rto_escalate_status": "",
        "rto_edd": "",
        "zone": "",
        "delivery_country": "India",
        "quick_pick": "",
        "other_charges": 0,
        "giftwrap_charges": 0,
        "discount": 0,
        "on_hold_reason": "",
        "comment": "",
        "awb_info_portals": [],
        "claim_id": null,
        "show_claim_history": false,
        "omuni2_enabled": 0,
        "invoice_no": "",
        "promise_courier_id": null,
        "is_passthrough": false,
        "is_allopathic": false,
        "quick_eligible": false,
        "manifest_id": "",
        "manifest_generated": false,
        "exchange_awb": null,
        "exchange_status": null,
        "awb_data": {
            "charges": {
                "zone": "",
                "cod_charges": "",
                "applied_weight_amount": "",
                "freight_charges": "",
                "applied_weight": "",
                "charged_weight": "",
                "charged_weight_amount": "",
                "charged_weight_amount_rto": "",
                "applied_weight_amount_rto": "",
                "service_type_id": ""
            }
        },
        "first_out_for_delivery_date": "",
        "picked_up_date": "",
        "brand_name": "WOC- World Of Care",
        "escalation_history": [],
        "marketplace_id": "",
        "marketplace_name": "",
        "expected_remittance_date": {
            "start_date": null,
            "end_date": null
        },
        "cluster_code": "",
        "allow_return_exchange": false,
        "is_revenue_assured_opt": false
    },





























    {
        "id": 885745723,
        "channel_id": 6593295,
        "last_mile_awb": null,
        "show_last_mile_label_download": 1,
        "last_mile_awb_track_url": null,
        "last_mile_courier_name": null,
        "channel_name": "WOC- World Of Care (Shopify)",
        "base_channel_code": "SH",
        "channel_order_id": "1009",
        "customer_name": "deepesh bairagi",
        "customer_email": "deepeshbairagi53@gmail.com",
        "customer_phone": "8853850773",
        "customer_address": "100, महात्मा गाँधी मार्ग",
        "customer_address_2": "block colony mandi sehore",
        "customer_city": "Indore",
        "customer_state": "Madhya Pradesh",
        "customer_pincode": "452001",
        "customer_country": "India",
        "customer_latitude": null,
        "customer_longitude": null,
        "customer_alternate_phone": "",
        "pickup_location": "Primary",
        "package_instructions": null,
        "order_type": null,
        "payment_status": "paid",
        "total": "999.00",
        "tax": "0.00",
        "sla": "2 days",
        "shipping_method": "SR",
        "ship_type": "",
        "rto_risk": "low",
        "return_pickup_data": "",
        "expedited": 0,
        "status": "CANCELED",
        "status_code": 5,
        "eway_bill_number": "",
        "eway_required": false,
        "awd_etds": null,
        "master_status": "",
        "payment_method": "prepaid",
        "cod_recieved_hover_text": "",
        "change_payment_mode": false,
        "is_international": 0,
        "document_status": 1,
        "international_b2b": "",
        "international_order_type": "",
        "is_order_custom": "",
        "purpose_of_shipment": 1,
        "channel_created_at": "6 Jul 2025, 01:04 AM",
        "created_at": "6 Jul 2025, 01:05 AM",
        "updated_at": "6 Jul 2025, 01:12 AM",
        "updated_on": "",
        "pickup_boy_name": "",
        "pickup_boy_contact_no": "",
        "products": [
            {
                "id": 1311876678,
                "channel_order_product_id": "15104019660969",
                "name": "Woc Panchgavya Ayurvedic Herbal Hair Oil",
                "channel_sku": "44412894576809",
                "quantity": 1,
                "product_id": 213068212,
                "available": "0",
                "status": "CANCELED",
                "price": "999.00",
                "product_cost": "999.00",
                "status_code": 5,
                "hsn": "",
                "is_allopathic": false,
                "discount": 0,
                "discount_including_tax": 0,
                "selling_price": 999,
                "mrp": 999,
                "tax_percentage": 0,
                "description": null
            }
        ],
        "shipments": [
            {
                "id": 882074215,
                "isd_code": "+91",
                "courier": "",
                "is_sr_recommended": false,
                "sr_courier_name": "",
                "courier_id": "",
                "shipping_charges": "",
                "weight": 0,
                "dimensions": "0x0x0",
                "shipped_date": null,
                "pickup_scheduled_date": "0000-00-00 00:00:00",
                "pickedup_timestamp": null,
                "pickup_token_number": null,
                "awb": "",
                "rto_awb": "",
                "return_awb": "",
                "volumetric_weight": 0,
                "pod": null,
                "etd": "0000-00-00 00:00:00",
                "saral_etd": "NA",
                "rto_delivered_date": "0000-00-00 00:00:00",
                "delivered_date": null,
                "etd_escalation_btn": false,
                "rto_initiated_date": "0000-00-00 00:00:00",
                "package_images": "",
                "weight_action": null,
                "status": 8,
                "pickup_id": "",
                "delivery_executive_name": "",
                "delivery_executive_number": "",
                "delay_reason": "",
                "product_quantity": 1,
                "total": "999.00",
                "sub_status": null,
                "cost": "0.00",
                "awb_assign_date": null
            }
        ],
        "cod": 0,
        "activities": [
            "ORDER_FETCHED",
            "CUSTOM",
            "CANCALLED_ON_SHIPROCKET_FROM_CHANNEL",
            "ORDER_CANCELLED"
        ],
        "allow_return": 0,
        "is_incomplete": 1,
        "errors": {
            "shipping_city": "Customer city is invalid, Language other than english is not supported."
        },
        "pickup_exception_reason": "",
        "show_escalation_btn": 0,
        "is_via_indiapost_courier": false,
        "show_escalation_btn_international": 0,
        "escalation_status": "",
        "escalation_id": null,
        "pii_removed": 0,
        "allow_multiship": 0,
        "others": {
            "name": "#1009",
            "test": true,
            "token": "f67f2390138e322c5e6bac41ee91ef14",
            "weight": "",
            "gateway": "bogus",
            "refunds": [],
            "user_id": null,
            "closed_at": null,
            "confirmed": true,
            "reference": "",
            "tax_lines": [],
            "cart_token": "Z2NwLWFzaWEtc291dGhlYXN0MTowMUpaME5BOEU3TjBOOVNIRkdKUDhNU0UwMg",
            "checkout_id": 29322154311849,
            "location_id": null,
            "source_name": "web",
            "api_order_id": 6347669012649,
            "billing_city": "इंदौर",
            "billing_name": "deepesh bairagi",
            "cancelled_at": null,
            "company_name": null,
            "payment_code": "bogus",
            "billing_email": "deepeshbairagi53@gmail.com",
            "billing_phone": "+918853850773",
            "billing_state": "Madhya Pradesh",
            "cancel_reason": null,
            "contact_email": "deepeshbairagi53@gmail.com",
            "currency_code": "INR",
            "checkout_token": "bfa58fc1643922c245f8947d7af39a19",
            "customer_gstin": null,
            "discount_codes": [],
            "referring_site": "",
            "subtotal_price": "999.00",
            "taxes_included": true,
            "billing_address": "100, महात्मा गाँधी मार्ग",
            "billing_company": null,
            "billing_country": "India",
            "billing_pincode": "452001",
            "note_attributes": [],
            "billing_isd_code": null,
            "is_webhook_order": true,
            "shipping_charges": "0.00",
            "billing_address_2": "block colony mandi sehore",
            "is_order_verified": 0,
            "is_webhook_update": true,
            "order_verified_at": "",
            "processing_method": "",
            "srf_shipping_meta": "",
            "fulfillment_status": null,
            "payment_gateway_names": [
                "bogus"
            ],
            "store_rush_promise_sla": "",
            "billing_alternate_phone": "",
            "buyer_accepts_marketing": true,
            "checkout_shipping_title": "",
            "checkout_shipping_method": "Standard",
            "utm_and_tracking_details": "{\"status\":\"\",\"awb\":\"\",\"tracking_url\":\"\",\"tracking_company\":\"\"}"
        },
        "package_list": {
            "packages": [],
            "selected": false,
            "select_item": false,
            "all_packages": []
        },
        "pickup_address_detail": {
            "id": 7766292,
            "pickup_code": "Primary",
            "gstin": null,
            "invoice_prefix": null,
            "invoice_serial": null,
            "address": "33A, MPIDC, Industrial Area ",
            "address_2": "Badiyakhedi",
            "address_type": null,
            "city": "Sehore",
            "state": "Madhya Pradesh",
            "country": "India",
            "pin_code": "466001",
            "email": null,
            "phone": "",
            "phone_verified": 0,
            "alternate_phone": null,
            "name": null,
            "company_id": 6011441,
            "status": 2,
            "rto_address_id": null,
            "delhivery_clientware_id": null,
            "delhivery_surface_clientware_id": null,
            "delhivery_surface_standard_clientware_id": null,
            "delhivery_surface_lite_clientware_id": null,
            "delhivery_surface_10kg_clientware_id": null,
            "delhivery_surface_20kg_clientware_id": null,
            "sx_delhivery_clientware_id": null,
            "sx_delhivery_surface_clientware_id": null,
            "sx4_delhivery_surface_clientware_id": null,
            "sx3_delhivery_surface_clientware_id": null,
            "sx2_delhivery_surface_clientware_id": null,
            "sx1_delhivery_surface_clientware_id": null,
            "created_at": "2025-04-06T09:05:54.000000Z",
            "updated_at": "2025-04-06T09:05:54.000000Z",
            "gati_surface_customer_vendor_code": null,
            "gati_sg_customer_vendor_code": null,
            "delhivery_flash_air_clientware_id": null,
            "updated_on": "2025-04-06 09:05:54",
            "lat": null,
            "long": null,
            "delhivery_essential_5kg_clientware_id": null,
            "warehouse_code": null,
            "gati_surface_10kg_customer_vendor_code": null,
            "extra_info": null,
            "delhivery_documents_clientware_id": null,
            "delhivery_documents_250gm_clientware_id": null
        },
        "rto_address": [],
        "re_escalate": 0,
        "seller_request": null,
        "engage": "NA",
        "total_dead_weight": null,
        "total_volumetric_weight": null,
        "total_order_value": null,
        "boxes": null,
        "order_tag": [],
        "international_order_tag": [],
        "is_return": 0,
        "is_b2b": false,
        "is_insurance_opt": false,
        "has_calls": false,
        "pickup_booked_date": null,
        "delivery_delayed": false,
        "delay_reason": "",
        "delay_reason_code": "",
        "etd_date": null,
        "out_for_delivery_date": null,
        "delivered_date": null,
        "product_quantity": 1,
        "rto_prediction": "",
        "rto_show": 0,
        "rto_reason": "",
        "rto_escalate": 0,
        "rto_re_escalate": 0,
        "rto_escalate_history": 0,
        "rto_escalate_status": "",
        "rto_edd": "",
        "zone": "",
        "delivery_country": "India",
        "quick_pick": "",
        "other_charges": 0,
        "giftwrap_charges": 0,
        "discount": 0,
        "on_hold_reason": "",
        "comment": "",
        "awb_info_portals": [],
        "claim_id": null,
        "show_claim_history": false,
        "omuni2_enabled": 0,
        "invoice_no": "",
        "promise_courier_id": null,
        "is_passthrough": false,
        "is_allopathic": false,
        "quick_eligible": false,
        "manifest_id": "",
        "manifest_generated": false,
        "exchange_awb": null,
        "exchange_status": null,
        "awb_data": {
            "charges": {
                "zone": "",
                "cod_charges": "",
                "applied_weight_amount": "",
                "freight_charges": "",
                "applied_weight": "",
                "charged_weight": "",
                "charged_weight_amount": "",
                "charged_weight_amount_rto": "",
                "applied_weight_amount_rto": "",
                "service_type_id": ""
            }
        },
        "first_out_for_delivery_date": "",
        "picked_up_date": "",
        "brand_name": "WOC- World Of Care",
        "escalation_history": [],
        "marketplace_id": "",
        "marketplace_name": "",
        "expected_remittance_date": {
            "start_date": null,
            "end_date": null
        },
        "cluster_code": "",
        "allow_return_exchange": false,
        "is_revenue_assured_opt": false
    }
]